### ISSUE TITLE
417 Client Error when trying to download epub

### ISSUE THREAD

**Issue by Mett-mit-Zwiebel** [gvellut/jncep#53]
**Describe the bug**
When I try to download a part from JNC Nina I get an error. This error is only pesent in the nina brach J-Novel Club works fine.

**Expected behavior**
Part should be downloaded

**To Reproduce**
jncep -d epub --email MYEMAIL --password MYPASSWORD https://jnc-nina.eu/read/the-eminence-in-shadow-band-01-teil-1

**Debug trace**
```
2024-08-29 23:36:05,777 jncep.utils  WARNING  Login with email '[highlight]p*******************@g****.com[/]'...
2024-08-29 23:36:06,205 jncep.utils  ERROR    *** An unrecoverable error occured ***
2024-08-29 23:36:06,205 jncep.utils  ERROR    417 Client Error: Expectation Failed for url: https://api.jnc-nina.eu/app/v2alpha/auth/login?format=json
2024-08-29 23:36:06,208 jncep.cli    DEBUG    Traceback (most recent call last):
   File "C:\Users\Anwender\AppData\Local\Programs\Python\Python311\Lib\site-packages\jncep-46-py3.11.egg\jncep\cli\base.py", line 17, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
   File "C:\Users\Anwender\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\Anwender\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\Anwender\AppData\Local\Programs\Python\Python311\Lib\site-packages\jncep-46-py3.11.egg\jncep\trio_utils.py", line 37, in wrapper
    return trio.run(partial(f, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\Anwender\AppData\Local\Programs\Python\Python311\Lib\site-packages\trio\_core\_run.py", line 1932, in run
    raise runner.main_task_outcome.error
   File "C:\Users\Anwender\AppData\Local\Programs\Python\Python311\Lib\site-packages\jncep-46-py3.11.egg\jncep\cli\epub.py", line 82, in generate_epub
    async with core.JNCEPSession(email, password) as session:
   File "C:\Users\Anwender\AppData\Local\Programs\Python\Python311\Lib\site-packages\jncep-46-py3.11.egg\jncep\core.py", line 72, in __aenter__
    await self.login(self.email, self.password)
   File "C:\Users\Anwender\AppData\Local\Programs\Python\Python311\Lib\site-packages\jncep-46-py3.11.egg\jncep\core.py", line 104, in login
    token = await self.api.login(email, password)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "C:\Users\Anwender\AppData\Local\Programs\Python\Python311\Lib\site-packages\jncep-46-py3.11.egg\jncep\jnclabs.py", line 151, in login
    r.raise_for_status()
   File "C:\Users\Anwender\AppData\Local\Programs\Python\Python311\Lib\site-packages\asks\response_objects.py", line 47, in raise_for_status
    raise BadStatus(
 asks.errors.BadStatus: 417 Client Error: Expectation Failed for url: https://api.jnc-nina.eu/app/v2alpha/auth/login?format=json
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - Python version: 3.11.9
 - JNCEP version: v46 (Nina)

**Comment by Mett-mit-Zwiebel** [comment]
It seems that my Email was not verified after I recently changed it. After verifying it worked.
