### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Eterale** [gvellut/jncep#56]
**Describe the bug**
With every command I get an error with : 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Scripts\jncep.exe\__main__.py", line 4, in <module>
    from jncep.jncep import main
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\site-packages\jncep\jncep.py", line 6, in <module>
    from .cli.config import config_manage
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\site-packages\jncep\cli\config.py", line 5, in <module>
    from .. import config, track, utils
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\site-packages\jncep\track.py", line 11, in <module>
    from . import config, core, jncweb, spec, utils
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\site-packages\jncep\core.py", line 17, in <module>
    from . import epub, jnclabs, jncweb, spec, utils
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\site-packages\jncep\jnclabs.py", line 6, in <module>
    import asks
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\site-packages\asks\__init__.py", line 5, in <module>
    from .base_funcs import *
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\site-packages\asks\base_funcs.py", line 8, in <module>
    from .sessions import Session
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\site-packages\asks\sessions.py", line 16, in <module>
    from .request_object import RequestProcessor
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\site-packages\asks\request_object.py", line 31, in <module>
    _BOUNDARY = "8banana133744910kmmr13a56!102!" + str(randint(1e3, 9e3))
                                                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matis\AppData\Local\Programs\Python\Python312\Lib\random.py", line 301, in randrange
    istart = _index(start)
             ^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

**To Reproduce**
Every command I do

**Debug trace**
Because of the bug, I can't

**Environment (please complete the following information):**
 - OS: Windows 11
 - Python version: Python 3.12.7
 - JNCEP version: v46

**Comment by H0R1Z0N** [comment]
See the bug report #45 for the fix.

**Comment by H0R1Z0N** [comment]
Update, i install the tmpfix branch using "pip install git+https://github.com/gvellut/jncep.git@tmpfix" and it seem ask was not the issue, unless it's requiring another version. It seem to point to trio, updating trio don't fix it either.

`/home/hnt/.local/lib/python3.12/site-packages/trio/_core/_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(
Traceback (most recent call last):
  File "/home/hnt/.local/bin/jncep", line 5, in <module>
    from jncep.jncep import main
  File "/home/hnt/.local/lib/python3.12/site-packages/jncep/jncep.py", line 6, in <module>
    from .cli.config import config_manage
  File "/home/hnt/.local/lib/python3.12/site-packages/jncep/cli/config.py", line 5, in <module>
    from .. import config, track, utils
  File "/home/hnt/.local/lib/python3.12/site-packages/jncep/track.py", line 11, in <module>
    from . import config, core, jncweb, spec, utils
  File "/home/hnt/.local/lib/python3.12/site-packages/jncep/core.py", line 18, in <module>
    from . import epub, jnclabs, jncweb, spec, utils
  File "/home/hnt/.local/lib/python3.12/site-packages/jncep/jnclabs.py", line 6, in <module>
    import asks
  File "/home/hnt/.local/lib/python3.12/site-packages/asks/__init__.py", line 5, in <module>
    from .base_funcs import *
  File "/home/hnt/.local/lib/python3.12/site-packages/asks/base_funcs.py", line 8, in <module>
    from .sessions import Session
  File "/home/hnt/.local/lib/python3.12/site-packages/asks/sessions.py", line 16, in <module>
    from .request_object import RequestProcessor
  File "/home/hnt/.local/lib/python3.12/site-packages/asks/request_object.py", line 31, in <module>
    _BOUNDARY = "8banana133744910kmmr13a56!102!" + str(randint(1e3, 9e3))
                                                       ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/random.py", line 301, in randrange
    istart = _index(start)
             ^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer
`
Ask and Trio have been attempted to be updated, still won't work.

**Comment by H0R1Z0N** [comment]
Baremetal Fedora 40 python 3.12, i normally use arch, no virtual-env of
python nor any docker

**Comment by gvellut** [comment]
In the last released version (v48), version 3.12 should work too (unfortunately, not 3.13 since there is a bigger change, maybe for next version...).

**Comment by H0R1Z0N** [comment]
Update from the discord server of JNC 
![Screenshot from 2024-10-21 09-16-28](https://github.com/user-attachments/assets/27653848-254e-4f27-aaf2-90219d9eac81)
Seem they might be using 32bits integer instead of 64bits.

**Comment by gvellut** [comment]
I have released a new version: It should support Python 3.12, as well as 3.13.
