### ISSUE TITLE
Error trying to generate single epub volume

### ISSUE THREAD

**Issue by olee** [gvellut/jncep#63]
Trying to generate an epub for a single volume eg. `jncep epub https://j-novel.club/series/black-summoner#volume-19` generates the following error:

```
❯ jncep --debug epub https://j-novel.club/series/black-summoner#volume-19
2024-11-07 03:24:22,443 jncep.utils  WARNING  Login to J-Novel Club with email '[highlight]<redacted>[/]'...
2024-11-07 03:24:23,246 jncep.jncapi DEBUG    API J-Novel Club GET /app/v2/me params=None body=None skip=None
2024-11-07 03:24:23,414 jncep.utils  INFO     Logged in to J-Novel Club with email '[highlight]<redacted>[/]'
2024-11-07 03:24:23,414 jncep.utils  WARNING  ...
2024-11-07 03:24:23,415 jncep.utils  INFO     Logout...
2024-11-07 03:24:23,582 jncep.utils  ERROR    *** An unrecoverable error occured ***
2024-11-07 03:24:23,582 jncep.utils  ERROR    no such group
2024-11-07 03:24:23,583 jncep.cli    DEBUG    Traceback (most recent call last):
   File "/home/.../docker-services/calibre/jncep/jncep/cli/base.py", line 17, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
   File "/home/.../docker-services/calibre/jncep/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/.../docker-services/calibre/jncep/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/.../docker-services/calibre/jncep/jncep/cli/options.py", line 107, in wrapper
    f(*args, **kwargs)
   File "/home/.../docker-services/calibre/jncep/jncep/trio_utils.py", line 37, in wrapper
    return trio.run(partial(f, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/.../docker-services/calibre/jncep/.venv/lib/python3.11/site-packages/trio/_core/_run.py", line 2407, in run
    raise runner.main_task_outcome.error
   File "/home/.../docker-services/calibre/jncep/jncep/cli/epub.py", line 87, in generate_epub
    jnc_resource = jncweb.resource_from_url(jnc_url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/.../docker-services/calibre/jncep/jncep/jncweb.py", line 80, in resource_from_url
    (series_slug, int(m.group(2))),
                      ^^^^^^^^^^
 IndexError: no such group
```

**Environment (please complete the following information):**
 - OS: linux
 - Python version: 3.11.2
 - JNCEP version: v50 (current master branch)

**Comment by gvellut** [comment]
Thank you for the bug report.

I have corrected it.
