### ISSUE TITLE
Fails to run in Python 3.13. Requires trio refactoring

### ISSUE THREAD

**Issue by talisein** [gvellut/jncep#65]
**Describe the bug**
Running jncep with no arguments on python 3.13 raises the exception below. It seems the oldest version of trio that supports 3.13 is 0.26.0. If I force install that, I can run jncep with no arguments. However, running jncep to try and download an epub fails, because MultiError was removed in trio 0.24.0. So some refactoring to the new trio api will be required. 

```
Traceback (most recent call last):
  File "/usr/local/bin/jncep", line 5, in <module>
    from jncep.jncep import main
  File "/usr/local/lib/python3.13/site-packages/jncep/jncep.py", line 6, in <module>
    from .cli.config import config_manage
  File "/usr/local/lib/python3.13/site-packages/jncep/cli/config.py", line 5, in <module>
    from .. import config, track, utils
  File "/usr/local/lib/python3.13/site-packages/jncep/track.py", line 11, in <module>
    from . import config, core, jncweb, spec, utils
  File "/usr/local/lib/python3.13/site-packages/jncep/core.py", line 16, in <module>
    import trio
  File "/usr/local/lib/python3.13/site-packages/trio/__init__.py", line 71, in <module>
    from ._path import Path
  File "/usr/local/lib/python3.13/site-packages/trio/_path.py", line 134, in <module>
    class Path(metaclass=AsyncAutoWrapperType):
  File "/usr/local/lib/python3.13/site-packages/trio/_path.py", line 85, in __init__
    type(cls).generate_forwards(cls, attrs)
  File "/usr/local/lib/python3.13/site-packages/trio/_path.py", line 102, in generate_forwards
    raise TypeError(attr_name, type(attr))
TypeError: ('parser', <class 'module'>)
```

**Environment (please complete the following information):**
 - OS: Fedora 41
 - Python version: 3.13
 - JNCEP version: v49

**Comment by gvellut** [comment]
Thank you for your feedback.

I had noticed the issue with Python 3.13. It is currently fixed in the development version (master) so you can use that if you can't wait. But I will try to make a release soon.

**Comment by gvellut** [comment]
I have finally released a new version: It should support 3.13.
